all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection: lxd
    ansible_user: root
    ansible_bacome: no
  children:
    local:
      vars:
        ansible_lxd_remote: local
        ansible_lxd_project: default
      hosts:
        blackarch: